import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import './globals.css';
import theme from '@/theme/theme';
import { ThemeProvider } from '@mui/material';
import ReactQueryProvider from '@/utils/provider/ReactQueryProvider';
import SessionWrapper from '@/components/auth/SessionWrapper';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper>
          <ReactQueryProvider>
            <ReactQueryDevtools />
            <AppRouterCacheProvider>
              <ThemeProvider theme={theme}>{children}</ThemeProvider>
            </AppRouterCacheProvider>
          </ReactQueryProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
