import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import './globals.css';
import theme from '@/theme/theme';
import { ThemeProvider } from '@mui/material';
import ReactQueryProvider from '@/provider/ReactQueryProvider';
import SessionWrapper from '@/components/auth/SessionWrapper';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import CartProvider from '@/context/cart/CartContext';
import WishListProvider from '@/context/WishListContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    default: 'Shoes Shop',
    template: '%s | Shoes Shop',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper>
          <ReactQueryProvider>
            <ReactQueryDevtools />
            <AppRouterCacheProvider>
              <ThemeProvider theme={theme}>
                <CartProvider>
                  <WishListProvider>{children}</WishListProvider>
                </CartProvider>
              </ThemeProvider>
            </AppRouterCacheProvider>
          </ReactQueryProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
