name: Run Unit Tests
on: 
  push:
    branches: 
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests with Coverage
        run: npm test -- --coverage --collectCoverageFrom='src/**/*.{ts,tsx}'

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-report
          path: output/test-coverage.html

      